### ISSUE TITLE
Building problem

### ISSUE THREAD

**Issue by xePixTvx** [shehryar49/pltSFML#1]
Hey :)
It seems im to stupid to build it xD
do you have a compiled version of it by any chance?(win64)

**Comment by shehryar49** [comment]
You need to have plutonium installed on  your system. Then you can use plutonium's package manager fiza to install sfml module.
Run the following commands in cmd
```
    cd C:\plutonium

    plutonium fiza.plt install sfml
```
This will install the sfml module. You can simply import and use it

**Comment by xePixTvx** [comment]
Worked

Thank you :)

**Comment by shehryar49** [comment]
No problem
